name: GitHub-Actions-Test-Manual-Trigger

on: workflow_dispatch

jobs:
  oblige:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        run: wget https://sourceforge.net/projects/oblige/files/Oblige/7.70/oblige-770-source.zip

      - name: Extract source code
        run: unzip oblige-770-source.zip

      - name: Build
        run: |
          cd Oblige-7.70-source
          sudo apt update
          sudo apt install libfltk1.3-dev zlib1g-dev
          wget https://raw.githubusercontent.com/zurg3/github-actions-test/master/OBLIGE/oblige.patch
          patch -p1 < oblige.patch
          make

      - name: Generate WAD
        run: |
          cd Oblige-7.70-source
          wget https://raw.githubusercontent.com/zurg3/github-actions-test/master/OBLIGE/my_config.txt
          ./Oblige --batch OUTPUT.wad --load my_config.txt

      - name: Upload WAD
        uses: actions/upload-artifact@v7
        with:
          path: Oblige-7.70-source/OUTPUT.wad
          archive: false

  amneziawg-windows-client:
    runs-on: windows-latest
    env:
      AWG_VERSION: "2.0.1"
      AWG_ARCH: "amd64"
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: amnezia-vpn/amneziawg-windows-client
          ref: ${{ env.AWG_VERSION }}

      - name: Build client
        shell: cmd
        run: build.bat

      - name: Build installer
        shell: cmd
        run: installer/build.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: installer/dist/amneziawg-${{ env.AWG_ARCH }}-${{ env.AWG_VERSION }}.msi
          archive: false
